# Defined hosts and paths for investigating
integrity_checks:
  - agent: all
    directories:
      - /opt/something
      - /opt/file.md

# Wazuh credentials
initial_user: "admin"
initial_pass: "SecretPassword"